 ## 日志配置
logging:
  level:
    root: info
    com.hywx.gw.userservice: debug

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: ${consul.url} #consul 注册中心地址
      port: 8500
      discovery:
        register: true
        failFast: true
        enabled: true
        register-health-check: true
        hostname: ${localhostIp}  #本机地址
        serviceName: ${spring.application.name}
        instanceId: gateway_mp
        tags: service,gateway
        healthCheckPath: /actuator/health
        health-check-interval: 10s

zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: auth-server
      sensitiveHeaders: "*"
    system:
      path: /system/**
      serviceId: user-service
      sensitiveHeaders: "*"
    duty:
      path: /duty/**
      serviceId: duty-service
      sensitiveHeaders: "*"
    test:
      path: /test/**
      serviceId: hywx-server-test
      sensitiveHeaders: "*"
    taskplan:
      path: /taskplan/**
      serviceId: taskplan-service
      sensitiveHeaders: "*"
    meteorological:
      path: /meteorological/**
      serviceId: meteorological-service
      sensitiveHeaders: "*"
    situation:
      path: /situation/**
      serviceId: situation-service
      sensitiveHeaders: "*"
  retryable: true  #开启重试机制
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  SendErrorFilter:
      error:
        disable: true

ribbon:
  ReadTimeout: 10000

#端口配置
server:
  port: 30001
#  servlet:
#    context-path: /auth-server/v1


management:
  endpoints:
    web:
      exposure:
        include: prometheus,info,health